#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if .Values.highAvailability.serviceMesh.virtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "eric-eo-evnfm-nbi.name" . }}-virtualservice
  labels: {{- include "eric-eo-evnfm-nbi.labels.extended-defaults" . | nindent 4 }}
  annotations: {{- include "eric-eo-evnfm-nbi.annotations" . | nindent 4 }}
spec:
  hosts:
    - {{ template "eric-eo-evnfm-nbi.name" . }}
  http:
    - match:
        - method:
            exact: GET
          uri:
            regex: /vnflcm/.*/vnf_instances/?
        - method:
            exact: GET
          uri:
            regex: /vnflcm/.*/vnf_instances/.*
        - method:
            exact: GET
          uri:
            regex: /vnfm/container/api/.*/resources/.*/pods
      retries:
        attempts: {{ .Values.highAvailability.serviceMesh.routes.getVnfInstances.retries.maxAttempts }}
        retryOn: 5xx,reset,gateway-error,connect-failure
      timeout: {{ .Values.highAvailability.serviceMesh.routes.getVnfInstances.timeout }}
      route:
        - destination:
            host: {{ template "eric-eo-evnfm-nbi.name" . }}
            subset: {{ template "eric-eo-evnfm-nbi.name" . }}-v1

    - match:
        - method:
            exact: GET
          uri:
            prefix: /
      retries:
        attempts: {{ .Values.highAvailability.serviceMesh.routes.get.retries.maxAttempts }}
        perTryTimeout: {{ .Values.highAvailability.serviceMesh.routes.get.retries.perTryTimeout }}
        retryOn: 5xx,reset,gateway-error,connect-failure
      timeout: {{ .Values.highAvailability.serviceMesh.routes.get.timeout }}
      route:
        - destination:
            host: {{ template "eric-eo-evnfm-nbi.name" . }}
            subset: {{ template "eric-eo-evnfm-nbi.name" . }}-v1

    - match:
        - method:
            exact: PUT
          uri:
            prefix: /
        - method:
            exact: PATCH
          uri:
            prefix: /
      retries:
        attempts: {{ .Values.highAvailability.serviceMesh.routes.putPatch.retries.maxAttempts }}
        perTryTimeout: {{ .Values.highAvailability.serviceMesh.routes.putPatch.retries.perTryTimeout }}
        retryOn: 5xx,reset,gateway-error,connect-failure
      timeout: {{ .Values.highAvailability.serviceMesh.routes.putPatch.timeout }}
      route:
        - destination:
            host: {{ template "eric-eo-evnfm-nbi.name" . }}
            subset: {{ template "eric-eo-evnfm-nbi.name" . }}-v1

    - match: # Routing rules are evaluated in sequential order from top to bottom. Priority: 1
        - method:
            exact: POST
          uri:
            regex: /vnflcm/.*/vnf_instances/.*/.*Node/?
      retries:
        attempts: {{ .Values.highAvailability.serviceMesh.routes.postNode.retries.maxAttempts }}
        perTryTimeout: {{ .Values.highAvailability.serviceMesh.routes.postNode.retries.perTryTimeout }}
        retryOn: 5xx,reset,gateway-error,connect-failure,retriable-headers
      timeout: {{ .Values.highAvailability.serviceMesh.routes.postNode.timeout }}
      route:
        - destination:
            host: {{ template "eric-eo-evnfm-nbi.name" . }}
            subset: {{ template "eric-eo-evnfm-nbi.name" . }}-v1

    - match: # Priority: 0
        - method:
            exact: POST
          uri:
            regex: /vnflcm/.*/vnf_instances.*
      retries:
        attempts: {{ .Values.highAvailability.serviceMesh.routes.post.retries.maxAttempts }}
        perTryTimeout: {{ .Values.highAvailability.serviceMesh.routes.post.retries.perTryTimeout }}
        retryOn: 5xx,reset,gateway-error,connect-failure,retriable-headers
      timeout: {{ .Values.highAvailability.serviceMesh.routes.post.timeout }}
      route:
        - destination:
            host: {{ template "eric-eo-evnfm-nbi.name" . }}
            subset: {{ template "eric-eo-evnfm-nbi.name" . }}-v1

    - match:
        - method:
            exact: POST
          uri:
            regex: /vnflcm/.*/vnf_lcm_op_occs/.*
      retries:
        attempts: {{ .Values.highAvailability.serviceMesh.routes.post.retries.maxAttempts }}
        perTryTimeout: {{ .Values.highAvailability.serviceMesh.routes.post.retries.perTryTimeout }}
        retryOn: 5xx,reset,gateway-error,connect-failure,retriable-headers
      timeout: {{ .Values.highAvailability.serviceMesh.routes.post.timeout }}
      route:
        - destination:
            host: {{ template "eric-eo-evnfm-nbi.name" . }}
            subset: {{ template "eric-eo-evnfm-nbi.name" . }}-v1

    - match:
        - method:
            exact: POST
          uri:
            regex: /vnflcm/.*/clusterconfigs/?
      retries:
        attempts: {{ .Values.highAvailability.serviceMesh.routes.post.retries.maxAttempts }}
        perTryTimeout: {{ .Values.highAvailability.serviceMesh.routes.post.retries.perTryTimeout }}
        retryOn: 5xx,reset,gateway-error,connect-failure,retriable-headers
      timeout: {{ .Values.highAvailability.serviceMesh.routes.post.timeout }}
      route:
        - destination:
            host: {{ template "eric-eo-evnfm-nbi.name" . }}
            subset: {{ template "eric-eo-evnfm-nbi.name" . }}-v1

    - match:
        - method:
            exact: DELETE
          uri:
            prefix: /
      retries:
        attempts: {{ .Values.highAvailability.serviceMesh.routes.delete.retries.maxAttempts }}
        perTryTimeout: {{ .Values.highAvailability.serviceMesh.routes.delete.retries.perTryTimeout }}
        retryOn: 5xx,reset,gateway-error,connect-failure
      timeout: {{ .Values.highAvailability.serviceMesh.routes.delete.timeout }}
      route:
        - destination:
            host: {{ template "eric-eo-evnfm-nbi.name" . }}
            subset: {{ template "eric-eo-evnfm-nbi.name" . }}-v1

    - route:
        - destination:
            host: {{ template "eric-eo-evnfm-nbi.name" . }}
            subset: {{ template "eric-eo-evnfm-nbi.name" . }}-v1
{{- end }}